/*
 * RSS Feed Aggregator
 * This is an api for \"RSS Feed Aggregator\".  [View Subject](https://intra.epitech.eu/module/2016/M-EAP-650/PAR-9-1/acti-235029/project/file/RSS-feed-aggregator.pdf) or [Messenger group](https://www.messenger.com/t/552069568251252)  A successfull login or signup generate a key usable to authenticate request  This key is owned by one account, a request providing an apiKey should get result for the user owning this key. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Article;
import io.swagger.client.model.InlineResponse2002;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ArticleApi
 */
@Ignore
public class ArticleApiTest {

    private final ArticleApi api = new ArticleApi();

    
    /**
     * retrieve article feed id and article id (id correspond to 1st, 2nd, 3rd, 4th... article)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void articlesFeedIdArticleIdGetTest() throws ApiException {
        String feedId = null;
        String articleId = null;
        Article response = api.articlesFeedIdArticleIdGet(feedId, articleId);

        // TODO: test validations
    }
    
    /**
     * retrieve the lisT of articles in the feed
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void articlesFeedIdGetTest() throws ApiException {
        String feedId = null;
        List<InlineResponse2002> response = api.articlesFeedIdGet(feedId);

        // TODO: test validations
    }
    
}
